// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Connection struct {
	UserID          uuid.UUID    `json:"user_id"`
	ConnectedUserID uuid.UUID    `json:"connected_user_id"`
	CreatedAt       sql.NullTime `json:"created_at"`
}

type Expense struct {
	ID           uuid.UUID     `json:"id"`
	GroupID      uuid.NullUUID `json:"group_id"`
	Description  string        `json:"description"`
	CurrencyCode string        `json:"currency_code"`
	TotalAmount  string        `json:"total_amount"`
	CreatedBy    uuid.UUID     `json:"created_by"`
	CreatedAt    sql.NullTime  `json:"created_at"`
}

type ExpenseSplit struct {
	ID         uuid.UUID `json:"id"`
	ExpenseID  uuid.UUID `json:"expense_id"`
	UserID     uuid.UUID `json:"user_id"`
	PaidAmount string    `json:"paid_amount"`
	OwedAmount string    `json:"owed_amount"`
}

type Group struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	CreatedBy uuid.UUID    `json:"created_by"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type GroupMember struct {
	GroupID  uuid.UUID    `json:"group_id"`
	UserID   uuid.UUID    `json:"user_id"`
	JoinedAt sql.NullTime `json:"joined_at"`
}

type User struct {
	ID                  uuid.UUID      `json:"id"`
	Email               string         `json:"email"`
	Name                string         `json:"name"`
	CountryCode         sql.NullString `json:"country_code"`
	DefaultCurrencyCode sql.NullString `json:"default_currency_code"`
	CreatedAt           sql.NullTime   `json:"created_at"`
}
