// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddConnection(ctx context.Context, arg AddConnectionParams) error
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error)
	CreateExpenseSplit(ctx context.Context, arg CreateExpenseSplitParams) error
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetExpenseSplits(ctx context.Context, expenseID uuid.UUID) ([]ExpenseSplit, error)
	GetGroupMembers(ctx context.Context, groupID uuid.UUID) ([]uuid.UUID, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserBalances(ctx context.Context, userID uuid.UUID) ([]GetUserBalancesRow, error)
	GetUserExpenses(ctx context.Context, arg GetUserExpensesParams) ([]Expense, error)
	ListConnections(ctx context.Context, userID uuid.UUID) ([]User, error)
	ListGroups(ctx context.Context, userID uuid.UUID) ([]Group, error)
}

var _ Querier = (*Queries)(nil)
