// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addConnection = `-- name: AddConnection :exec
INSERT INTO connections (user_id, connected_user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddConnectionParams struct {
	UserID          uuid.UUID `json:"user_id"`
	ConnectedUserID uuid.UUID `json:"connected_user_id"`
}

func (q *Queries) AddConnection(ctx context.Context, arg AddConnectionParams) error {
	_, err := q.db.ExecContext(ctx, addConnection, arg.UserID, arg.ConnectedUserID)
	return err
}

const addGroupMember = `-- name: AddGroupMember :exec
INSERT INTO group_members (group_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddGroupMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, addGroupMember, arg.GroupID, arg.UserID)
	return err
}

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (group_id, description, currency_code, total_amount, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, group_id, description, currency_code, total_amount, created_by, created_at
`

type CreateExpenseParams struct {
	GroupID      uuid.NullUUID `json:"group_id"`
	Description  string        `json:"description"`
	CurrencyCode string        `json:"currency_code"`
	TotalAmount  string        `json:"total_amount"`
	CreatedBy    uuid.UUID     `json:"created_by"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, createExpense,
		arg.GroupID,
		arg.Description,
		arg.CurrencyCode,
		arg.TotalAmount,
		arg.CreatedBy,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Description,
		&i.CurrencyCode,
		&i.TotalAmount,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createExpenseSplit = `-- name: CreateExpenseSplit :exec
INSERT INTO expense_splits (expense_id, user_id, paid_amount, owed_amount)
VALUES ($1, $2, $3, $4)
`

type CreateExpenseSplitParams struct {
	ExpenseID  uuid.UUID `json:"expense_id"`
	UserID     uuid.UUID `json:"user_id"`
	PaidAmount string    `json:"paid_amount"`
	OwedAmount string    `json:"owed_amount"`
}

func (q *Queries) CreateExpenseSplit(ctx context.Context, arg CreateExpenseSplitParams) error {
	_, err := q.db.ExecContext(ctx, createExpenseSplit,
		arg.ExpenseID,
		arg.UserID,
		arg.PaidAmount,
		arg.OwedAmount,
	)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, created_by)
VALUES ($1, $2)
RETURNING id, name, created_by, created_at
`

type CreateGroupParams struct {
	Name      string    `json:"name"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, arg.Name, arg.CreatedBy)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, name, country_code, default_currency_code)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, name, country_code, default_currency_code, created_at
`

type CreateUserParams struct {
	ID                  uuid.UUID      `json:"id"`
	Email               string         `json:"email"`
	Name                string         `json:"name"`
	CountryCode         sql.NullString `json:"country_code"`
	DefaultCurrencyCode sql.NullString `json:"default_currency_code"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.CountryCode,
		arg.DefaultCurrencyCode,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CountryCode,
		&i.DefaultCurrencyCode,
		&i.CreatedAt,
	)
	return i, err
}

const getExpenseSplits = `-- name: GetExpenseSplits :many
SELECT id, expense_id, user_id, paid_amount, owed_amount FROM expense_splits WHERE expense_id = $1
`

func (q *Queries) GetExpenseSplits(ctx context.Context, expenseID uuid.UUID) ([]ExpenseSplit, error) {
	rows, err := q.db.QueryContext(ctx, getExpenseSplits, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseSplit
	for rows.Next() {
		var i ExpenseSplit
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseID,
			&i.UserID,
			&i.PaidAmount,
			&i.OwedAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupMembers = `-- name: GetGroupMembers :many
SELECT user_id FROM group_members WHERE group_id = $1
`

func (q *Queries) GetGroupMembers(ctx context.Context, groupID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, country_code, default_currency_code, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CountryCode,
		&i.DefaultCurrencyCode,
		&i.CreatedAt,
	)
	return i, err
}

const getUserBalances = `-- name: GetUserBalances :many
SELECT currency_code, SUM(paid_amount - owed_amount) as balance
FROM expenses e
JOIN expense_splits es ON e.id = es.expense_id
WHERE es.user_id = $1
GROUP BY currency_code
`

type GetUserBalancesRow struct {
	CurrencyCode string `json:"currency_code"`
	Balance      int64  `json:"balance"`
}

func (q *Queries) GetUserBalances(ctx context.Context, userID uuid.UUID) ([]GetUserBalancesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserBalances, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserBalancesRow
	for rows.Next() {
		var i GetUserBalancesRow
		if err := rows.Scan(&i.CurrencyCode, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserExpenses = `-- name: GetUserExpenses :many
SELECT e.id, e.group_id, e.description, e.currency_code, e.total_amount, e.created_by, e.created_at FROM expenses e
JOIN expense_splits es ON e.id = es.expense_id
WHERE es.user_id = $1 AND (e.group_id = $2 OR $2 IS NULL)
`

type GetUserExpensesParams struct {
	UserID  uuid.UUID     `json:"user_id"`
	GroupID uuid.NullUUID `json:"group_id"`
}

func (q *Queries) GetUserExpenses(ctx context.Context, arg GetUserExpensesParams) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, getUserExpenses, arg.UserID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Description,
			&i.CurrencyCode,
			&i.TotalAmount,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnections = `-- name: ListConnections :many
SELECT u.id, u.email, u.name, u.country_code, u.default_currency_code, u.created_at FROM users u
JOIN connections c ON u.id = c.connected_user_id
WHERE c.user_id = $1
`

func (q *Queries) ListConnections(ctx context.Context, userID uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listConnections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.CountryCode,
			&i.DefaultCurrencyCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT g.id, g.name, g.created_by, g.created_at FROM groups g
JOIN group_members gm ON g.id = gm.group_id
WHERE gm.user_id = $1
`

func (q *Queries) ListGroups(ctx context.Context, userID uuid.UUID) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
